services:
  envoy:
    image: envoyproxy/envoy:v1.30-latest
    command: ["-c", "/etc/envoy/envoy.yaml", "--log-level", "info"]
    ports:
      - "10000:10000"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
      - ./dist:/etc/envoy/wasm:ro

